apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-demo.fullname" . }}
spec:
  selector:
    app: {{ include "devops-demo.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
